<a href="https://colab.research.google.com/github/boss2002123/numpy/blob/main/july_9_00am.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")  #this is a python program to display a text

#comments

hello world


This is a python program to print a text


In [ ]:
print("apple\n1122") #for printing in newline

apple
1122


In [ ]:
print("apple")
print("1122")

apple
1122


In [ ]:
print("apple\t1122")

apple	1122


In [ ]:
a=5
b="apple"

print(a)

print(b)

5
apple


In [ ]:
#ord
print(ord("a"))
#chr
print(chr(97))

97
a


In [ ]:
#encode and decode

text="apple♥à"

en=text.encode()


de=en.decode()

print(en)
print(de)

b'apple\xe2\x99\xa5\xc3\xa0'
apple♥à


In [ ]:
#unicode

print("\u2234")

∴


In [ ]:
name="John Wick"

print(name)

age=40

print(age)

pi=3.14

print(pi)

John Wick
40
3.14


In [ ]:
#multiple variable assignment

a,b=12,34

In [ ]:
#wap to swap two numbers

a,b=2,3

a,b=b,a

print(a,b)
# print(b)

3 2


In [ ]:
#wap to print area of a circle with radious 2 and value of pi is 3.14

pi=3.14

r=2

area=pi*r*r

print("area of the circle is :",area)

area of the circle is : 12.56


In [ ]:
#wap to find perimeter of a circle

pi=3.14
r=5

print(2*pi*r)

31.400000000000002


In [ ]:
first_name="John"

last_name="Wick"

full_name=first_name+" "+last_name

print(full_name)

John Wick


In [ ]:
# name=input("Enter your name")
# name

password=input("enter your password")
print(password)

enter your passworduu
uu


In [ ]:
#wap to read first_name and last_name from the user and print full_name

first_name=input("Enter your first_name: ")

last_name=input("Enter your last_name: ")




print("full name is : ",first_name+" "+last_name)

Enter your first_name: dff
Enter your last_name: sf
full name is :  dff sf


In [ ]:
#read two numbers from the user and compute their sum
a=float(input("Enter the first number: "))
b=float(input("Enter the second number: "))
print(type(a))
# add=int(a)+int(b)

add=a+b
print("sum of two numbers is,a+b",add)

Enter the first number: 3
Enter the second number: 4
<class 'float'>
sum of two numbers is,a+b 7.0


In [ ]:
#type conversion and type casting

a=2.30

print(type(a))

<class 'float'>


In [ ]:
#read two numbers from the user and perform their difference

a=int(input("Enter the first number"))

b=int(input("Enter the second number"))

print(a-b)

Enter the first number3
Enter the second number4
-1


In [ ]:
#global and local varriables

x=100 #global varriables

def add():
  x=200 #local variable
  print("value of x inside teh function",x)
  print(x+1)



add()

print(x+1)

# print("value of x outside the function",x)

value of x inside teh function 200
201
101


In [ ]:
#data types in python

#intiger  1,2,3 .....  int()       type()
#float    2.4,2.6....  float()
#string   "text"       str()
#boolean  true/false
#none      none

In [ ]:
age=23

name="John"

height=3.14

married=False

print(type(age),type(name),type(height))

print(type(married))

<class 'int'> <class 'str'> <class 'float'>
<class 'bool'>


In [ ]:
a=12

b=10

a=20

print(a)

20


In [ ]:
#types of operators in python

#arethmetic operators(+,-,/,*,%,//,**)

a=3
b=2
print(a//b)
print(a**2)
print(a%b)

1
9
1


In [ ]:
#read two numbers from the user and perform all arithmetic operations

a=int(input("enter the first number"))
b=int(input("enter teh second number"))

print("sum of two number is: ",a+b)

enter the first number4
enter teh second number5
sum of two number is:  9


In [ ]:
#wap to find area of a square read the value of side from the user

s=int(input("Enter the value of side: "))

area=s**2

print("area of the square is ",area)

Enter the value of side: 6
area of the square is  36


In [ ]:
#relational/comparison operators ==,!=,>,<,>=,<= boolean

a=10
b=20

print(a==b)

print(a!=b)

print(a>b)
print(a<b)

print(a>=b)
print(a<=b)

False
True
False
True
False
True


In [ ]:
a="apple"
b="apple"

print(a==b)

print(a!=b)

True
False


In [ ]:
#assignment operator =,+=,-=,/=,*=....

a=20

a+=20  #a=a+20

a-=10

a/=10  #a=a/10
print(a)

3.0


In [ ]:
#logical operators and or not

a=10
b=20

print(a>b and a==b)
print(a>b or a==b)

print(not a>b)

False
False
True


In [ ]:
#operator precedence   P-parantesis,E-exponential,M-MULTIPLICATION,D-division,A-addition,S-subsraction  PEMDAS

print((4+2)*(2-1))

6


In [ ]:
#BITWISE OPERATOR and (&) or (|)
print(5&3)
print(5|3)

1
7


In [ ]:
#round()

a=4.5543323223212

print(round(a,2))

4.55


In [ ]:
#mebership operator in/not in

# s="python"

print("a" not in "python")

# l=[1,2,3,4]

# print(5 in l)

True


In [ ]:
#short-hand if      statement1 if cond1 true else statement 2

a=10

#print hai if a=10 else print hello

print("hai") if a==10 else print("hello")

hai


In [ ]:
#wap to print adult if age>20 else print minor


age=int(input("enter the age"))

print("adult") if age>20 else print("minor")

enter the age9
minor


In [ ]:
#wap to check a chr is vowel or not
v="aeiouAEIOU"
ch=input("enter the chr")
print("vowel") if ch in v else print("not vowel")

enter the chra
vowel


In [ ]:
#wap to read three number from the user and print their average

a=int(input("enter the first number"))
b=int(input("enter the second number"))
c=int(input("enter the third number"))

print((a+b+c)/3)

enter the first number3
enter the second number4
enter the third number5
4.0


In [ ]:
#wap to read two numbers from the user and print true if a>b else print false

a=float(input("enter the first number"))
b=float(input("enter the second number"))

print("true") if a>b else print("false")

enter the first number9
enter the second number8
true


In [ ]:
#wap to calculate n+n square +n cube

n=int(input("enter the number"))

a=n+n**2+n**3

print(a)

enter the number3
39


In [ ]:
#wap to convert celcious to farenheit using f=(c*9/5)+32

c=float(input("enter the temparature value in celcious"))

f=(c*9/5)+32

print("the farenheit value is: ",f)

enter the temparature value in celcious33
the farenheit value is:  91.4


In [ ]:
#identity operator  is/is not

a=2
b=2                            #int ,str ,tuple imutable cannot be changed  ==
                               #mutable can be changed list

print(a is b)
print(a==b)

True
True


In [ ]:
l1=[1,2,3] #l1
l2=[1,2,3] #l2

l1=l2

# print(l1==l2)

print(l1 is not l2)

False


In [ ]:
#wap to check a number is multiple of 3 or not

n=int(input("enter the number"))

print("multiple of 3") if n%3==0 else print("not multiple of 3")

enter the number3
multiple of 3


In [ ]:
#wap to check a number is odd or even

n=int(input("enter the number"))

print("even") if n%2==0 else print("odd")

enter the number3
odd


In [ ]:
#string  text

#string concatination  + operator

a="apple"
b="orange"

print("concatinated string is: ",a+b)

concatinated string is:  appleorange


In [ ]:
s="apple"

print(len(s))

5


In [ ]:
s="AppLe"

print(s.upper())

print(s.lower())

APPLE
apple


In [ ]:
s="aPPles aNd Oranges"

print(s.title())

print(s.capitalize())

print(s.swapcase())

Apples And Oranges
Apples and oranges
AppLES AnD oRANGES


In [ ]:
#find other string manipulation functions
s="apple"
print(s[0])  #forward indexing
print(s[4])
print(s[2])

a
e
p


In [ ]:
s[-5]  #backward indexing
s[-1]

'e'

In [ ]:
s="all apples are oranges"

#apples
print(s[4:10])
#are
print(s[11:14])
#alap
print(s[0:7:2])
#ora
print(s[15:18])
#e o
print(s[13:16])


apples
are
alap
ora
e o


In [ ]:
s="apple"

s[-3:-1]

s[-2:-4:-1]

s[-5::]
s[-1::-1]

'elppa'

In [ ]:
s="all oranges are grapes"

#grapes
s[-6::]
#segnaro
s[-12:-19:-1]
#all
s[-22:-19]
#lla
s[-20::-1]
#spr
s[-1:-6:-2]
#reverse full string
s[-1::-1]

'separg era segnaro lla'

In [ ]:
#wap to read a string from the user and reverse it

s=input("enter the string")

print(s[-1::-1])

enter the stringorange
egnaro


In [ ]:
#wap to check a string is palindrome or not
s=input("enter the string")

a=s[-1::-1]
print("palindrome") if s==a else print("not palindrome")

enter the stringmalayalam
palindrome


In [ ]:
#wap to find middle element in a given string

s="grape"

print(s[len(s)//2])

a


In [ ]:
#wap to count number of words in a string
s=" apples are oranges and "
a=s.strip() #used to remove white space from start and end \n
print(s.count("a"))
print(a)
print(a.count(" ")+1)

4
apples are oranges and
4


In [ ]:
s="all apples are apples are oranges"
s.replace("apples","oranges")

'all oranges are oranges are oranges'

In [ ]:
s="all-apples-are$apples$are oranges"

a=s.split("$")
print(type(a))
print(a)

<class 'list'>
['all-apples-are', 'apples', 'are oranges']


In [ ]:
#format

a=20

b="apple"

print("price of {1} is {0}".format(a,b))

price of apple is 20


In [ ]:
#read first_name from the user and print "length of first_name is value of length"

first_name=input("enter the first_name")

length=len(first_name)

print("length of {} is {}".format(first_name,length))

enter the first_namejohn
length of john is 4


In [ ]:
#fstring

a=20
b="apple"

print(f"price of {b} is {a}")

price of apple is 20


In [ ]:
#read last_name from the user and print its length using fstring

last_name="Wick"

print(f"length of {last_name} is {len(last_name)}")

length of Wick is 4


In [ ]:
#wap to count number of $ in the given string
s="p$tho$ is $ a goo$d $program$ing lan$gua$ge"

print(s.count("$"))

8


In [ ]:
# sorted()

s="apple"

a=sorted(s)
a

['a', 'e', 'l', 'p', 'p']

In [ ]:
#wap to check a number is positive negative or zero

n=int(input("enter teh number"))

if n>0:
  print("positive")
elif n==0:
  print("zero")

else:
  print("negative")

enter teh number0
zero


In [ ]:
#wap to print multiple of 5 and 7 if divisible by 5 and 7
#else print multiple of 5 if only divisible by 5
#otherwise print multiple of 7 only divisible by 7
#else print not multiple of 5 and 7
n=int(input("enter teh number"))

if n%5==0 and n%7==0:
  print("divisible by both")
elif n%5==0:
  print("multiple of 5")

elif n%7==0:
  print("multiple of 7")

else:
  print("not multiple of both")

enter teh number7
multiple of 7


In [ ]:
#wap to read three numbers from the user and print the largest

In [ ]:
#wap to calculate the grade of a student
#grade A if mark >90
#grade B if mark between 80 and 90 80<mark<=90
#grade C if mark between 80 and 70 70<mark<=80
#grade D i mark equal to 70
#otherwise failed

In [ ]:
#wap to remove third index element from a given string

s="orange"
n=int(input("enter teh index"))


a=s[0:n]
b=s[n+1:]

print(a+b)

enter teh index3
orage


In [ ]:
#range

print(list(range(1,10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#wap to print even numbers with in 0-10

for i in range(0,11,2):
  print(i)

0
2
4
6
8
10


In [ ]:
for i in range(0,11):
  if i%2==0:
    print(i,end=" ")

0 2 4 6 8 10 

In [ ]:
#wap to print multiple of 5 with in 0-100 horizontally

for i in range(0,101):
  if i%5==0:
    print(i,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 

In [ ]:
#collections in python
#list
#tuple
#dictionary
#set

In [ ]:
#list  [], Mutable data type ,changable, collection of same datatypes or different datatypes

# l=[1,2,3,4]

l=[1,"apple",2.39]

l[0]="orange"

l

['orange', 'apple', 2.39]

In [ ]:
l=[1,2,3,4,5]


print(l[2:5])

print(l[-1])

l.append("apple")

l.append(9)

l



[3, 4, 5]
5


[1, 2, 3, 4, 5, 'apple', 9]

In [ ]:
l=[9,2,4,8,6,1,7]

l.sort(reverse=True)

print(l)

[9, 8, 7, 6, 4, 2, 1]


In [ ]:
#wap to find second largest elemetn in a given list
l=[9,2,4,8,6,1,7]

l.sort()
print(l[-2])

8


In [ ]:
l=[9,2,4,8,6,1,7]

a=sorted(l)

print(a)

[1, 2, 4, 6, 7, 8, 9]


In [ ]:
l=[5,4,9,1,2]

# print(l[-1::-1])

l.reverse()

print(l)

[2, 1, 9, 4, 5]


In [ ]:
l=[3,4,2,7,4]

print(max(l))
print(min(l))
print(len(l))
print(l.count(4))

7
2
5
2


In [ ]:
#create a new list of even numbers for existing list
even=[]
l=[4,2,3,6,7,8,9]

for i in l:
  if i%2==0:
    even.append(i)


print(even)

[4, 2, 6, 8]


In [ ]:
#wap to create list of odd numbers from existing list

l=[4,2,3,6,7,8,9]

In [ ]:
#wap to remove duplicate element in a list
du=[]
l=[1,1,1,2,2,8,6,6,6,6]

for i in l:
  if i not in du:
    du.append(i)

du

[1, 2, 8, 6]

In [ ]:
#read any three names from the user and add it into a list

l=[]
for i in range(3):
  print(i)
  n=input()
  l.append(n)

print(l)

0
apple
1
orang
2
mgano
['apple', 'orang', 'mgano']


In [ ]:
#wap to print sum of elements in a list

s=0
l=[4,3,5,3]

for i in l:
  s=s+i


s



15

In [ ]:
1stname="apple"

SyntaxError: invalid decimal literal (ipython-input-3115418099.py, line 1)

In [ ]:
first name="orange"

SyntaxError: invalid syntax (ipython-input-1585941222.py, line 1)

In [ ]:
l=[4,3,5,3]

print(sum(l))

l.index(5)

l.remove(4) #particular elemetn
l

l.pop(1)  #based on index

l

15


[3, 3]

In [ ]:
l=[5,4,6,2,1]

l1=[3,4,5,6]

#remove element 6 without using remove function

i=l.index(6)

l.pop(i)
l

# l.extend(l1)
print(l+l1)

[5, 4, 2, 1, 3, 4, 5, 6]


In [ ]:
#tuple  ()  imutable tuple()

#create new tuple from an existing tuple which has only multiple of 3
l=[]
t=(1,2,3,9,6)

for i in t:
  if i%3==0:
    l.append(i)


t1=tuple(l)

print(type(t1))

<class 'tuple'>


In [ ]:
#read a list of elements from the user

l=[]

for i in range(3):
  e=input()
  l.append(e)

l

apple
ornage
mango


['apple', 'ornage', 'mango']

In [ ]:
l=tuple(input().split())
l

apple orange mango


('apple', 'orange', 'mango')

In [ ]:
#read a tuple from the user

In [ ]:
#wap to count multiple of 3 in a given tuple without using list
l=[]
t=(3,1,2,6,7,9)

for i in t:
  if i%3==0:
    l.append(i)

print(len(l))

3


In [ ]:
t=(3,1,2,6,7,9)

c=0

for i in t:
  if i%3==0:
    c=c+1

print(c)

3


In [ ]:
t=(3,1,2,6,7,9)

print(max(t))
print(min(t))
print(len(t))
print(t.count(9))

9
1
6
1


In [ ]:
#dictionary {} mutable  dict()  key-value pairs

student={"name":"john","class":12,"rollno":13}

print(type(student))

<class 'dict'>


In [ ]:
student["name"]

student['class']

12

In [ ]:
student['name']="jack"  #updating existing value

student['age']=24    #add a new element

student

{'name': 'jack', 'class': 12, 'rollno': 13, 'age': 24}

In [ ]:
print(len(student))

print(student.keys())

print(student.values())

print(student.items())

6
dict_keys(['name', 'class', 'rollno', 'age', 'height', 'weight'])
dict_values(['jack', 12, 13, 24, 123, 456])
dict_items([('name', 'jack'), ('class', 12), ('rollno', 13), ('age', 24), ('height', 123), ('weight', 456)])


In [ ]:
student.update({"height":123,"weight":456})

student

{'name': 'jack',
 'class': 12,
 'rollno': 13,
 'age': 24,
 'height': 123,
 'weight': 456}

In [ ]:
student.get("height")

123

In [ ]:
# student.pop("height")

# student

student.popitem()

student

{'name': 'jack', 'class': 12, 'rollno': 13}

In [ ]:
d={1:"apple",2:"orange",3:"mango"}

#display the dictionary

print(d)
#add new item 6:banana
d[6]="banana"
print(d)
#update the value of apple to grapes
d[1]="grapes"
print(d)
#delete grapes
d.pop(1)

{1: 'apple', 2: 'orange', 3: 'mango'}
{1: 'apple', 2: 'orange', 3: 'mango', 6: 'banana'}
{1: 'grapes', 2: 'orange', 3: 'mango', 6: 'banana'}


'grapes'

In [ ]:
d

{2: 'orange', 3: 'mango', 6: 'banana'}

In [ ]:
#wap to count each word in a given list
d={}
l=["hai","hai","hello","hello","hello","bye"]

for i in l:
  if i not in d:
    d[i]=1
  else:
    d[i]=d[i]+1

d

{'hai': 2, 'hello': 3, 'bye': 1}

In [ ]:
#set mutable {} unique elements set()

#wap to print unique elemtents from a given list

l=[1,1,1,2,3,3,3,5,5,5]

s=list(set(l))

s

[1, 2, 3, 5]

In [ ]:
s={1,2,3,4}

s.add(5)
s.add(2)

s.remove(4)

s.update({6,7,8})
s

{1, 2, 3, 5, 6, 7, 8}

In [ ]:
s1={1,2,4,5,6}
s2={5,6,7,8,9}

print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

{1, 2, 4, 5, 6, 7, 8, 9}
{5, 6}
{1, 2, 4}
{1, 2, 4, 7, 8, 9}


In [ ]:
#you are given a lsit of subjects for student assume one of the classroom is required for 1 subject how many classrooms are needed by all subjects

subject=["cs","cs","ai","ds"]

s=len(set(subject))
s

3

In [ ]:
#wap to read name and mark of three sutdents and store it in a dictionary

d={}

for i in range(3):
  name=input("Enter the name: ")
  mark=float(input("Enter the mark: "))
  d[name]=mark

Enter the name: john
Enter the mark: 23
Enter the name: boss
Enter the mark: 43
Enter the name: abu
Enter the mark: 87


In [ ]:
for k,v in d.items():
  print(k,v)

john 23.0
boss 43.0
abu 87.0


In [ ]:
#nested list (list of list)

l=[1,2,[3,4,["a","b"]],5,3]

#2

#[3,4,["a","b"]]

#["a","b"]

#"b"

#4

In [ ]:
l1=[{1:"apple",3:"mango"},{2:"orange"}]

l1[1]

l1[0][3]

'mango'

In [ ]:
#create a temparature converter if choice is
#1 convert celcios to farenheit f=c*(9/5)+32
#if choice is 2 convert farenheit teo celcious c=(f-32)*(5/9)

In [ ]:
#assign 7 to x and 3 to y then compute x+y*2
#swap a=100 and b=200
#check if width =10 and height =20 is width and heigt are equal
#extract world from hello world
#check if text="python" starts with py
#count how many l in hello
#replace cat with dog in phrase="I love cat"
#check if "123" is numeric
#check 5 exists in [1,2,3,4]
#convert "3.14" to float
#change 100 to a string
#transfrom "hello" into list of characters
#calculate 15% tip on bill=50
#what is 3*"A"+2*"B"
print(3*"A"+2*"B")
#Evaluvate [1,2,3][1:]
print([1,2,3][1:])

AAABB
[2, 3]


In [ ]:
bill=50

print(.15*bill)

7.5


In [ ]:
#walrus operator

print(.15*(bill:=20))

3.0


In [ ]:
# #increment x=7 by 3 without using + operator
# x=7
# x+=3
# #convert miles=5 to kilometers (1mile=1.60934) use walrus operator
# print((miles:=5)*1.60934)
# #print swap case of s="PyThon"
# s.swapcase()
# #check if s="hello" is all lowercase
# islower()
# #check if word="Python" end with "on"
# .endswith()
# #remove whitespaces from " hello "
# .strip()
# #split "apple,banana,cherry" at commas
# .split(",")
# #check if "123abc" is alpha numeric
# isalnum()
# #change the second element of l=[1,2,3] to 5
# l[1]=5
# #get index of "b" in ["a","b","c"]
# .index("b")
# #find smallest of two numbers
# min(a,b)
# #calculate hypotenuse of a right triangle with sides 3 and 4

a=3
b=4
c=(a**2+b**2)**.5

print(c)

5.0


In [ ]:
#wap to print 10 hai vertically

for i in range(10):
  print("hai")
  # print(i)

hai
hai
hai
hai
hai
hai
hai
hai
hai
hai


In [ ]:
#wap to print 10 hai horizontaly
for i in range(10):
  print("hai",end=" ")

hai hai hai hai hai hai hai hai hai hai 

In [ ]:
#wap to find sum of even numbers within 1-100 both including

s=0

for i in range(0,101,2):
  print(i,end=" ")
  s+=i

s

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 

2550

In [ ]:
#wap to find sum of odd numbers with in 1-20 both inclusive

s=0

for i in range(1,21):
  if i%2!=0:
    s=s+i

s

100

In [ ]:
#wap to print factorial of a number
n=int(input("enter the number"))

f=1
for i in range(1,n+1):
  f=f*i

f

enter the number5


120

In [ ]:
#wap to print multiplication table of 5 upto 15 rows

for i in range(1,16):
  print(f"{i} x 5 ={i*5}")

1 x 5 =5
2 x 5 =10
3 x 5 =15
4 x 5 =20
5 x 5 =25
6 x 5 =30
7 x 5 =35
8 x 5 =40
9 x 5 =45
10 x 5 =50
11 x 5 =55
12 x 5 =60
13 x 5 =65
14 x 5 =70
15 x 5 =75


In [ ]:
#wap to print factors of a given number

n=int(input("enter the number"))

for i in range(1,n+1):
  if n%i==0:
    print(i)

1
2
4
8


In [ ]:
#wap to count number of factors of a given number


n=int(input("enter the number"))
c=0
for i in range(1,n+1):
  if n%i==0:
    c+=1

if c==2:
  print("prime")

else:
  print("not prime")


enter the number2
prime


In [ ]:
l=[]
n=8
for i in range(1,n+1):
  if n%i==0:
    l.append(i)

print(len(l))

4


In [ ]:
l=[0,1]
n=6
for i in range(2,n):
  t=l[-1]+l[-2]
  l.append(t)


for i in l:
  print(i,end=" ")

0 1 1 2 3 5 

In [ ]:
f=0
s=1

for i in range(4):
  print(f,end=" ")
  t=f+s
  f=s
  s=t

0 1 1 2 

In [ ]:
#wap to find number of charecters in a string
#wap to find number of words in a string

In [ ]:
i=0

while i<10:
  print("hi")
  i+=1

hi
hi
hi
hi
hi
hi
hi
hi
hi
hi


In [ ]:
#wap to print odd numbers less than 50 using while loop

# i=1

# while i<50:
#   print(i)
#   i+=2



i=0

while i<50:
  if i%2!=0:
    print(i,end=" ")
  i+=1


1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 

In [ ]:
#wap to print fiste 10 natural numbers using while loop

i=1

while i<=10:
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#create a electricity bill
#if unit consumed upto 100(including) nocharge
#if unit consumed is greater than 100 and equal to 200 rs 5 per unit
#if unit consumed is greater than 200 rs 10 per unit
#find the total amount

In [ ]:
n=350

if n<=100:
  print("no charge")

elif n>100 and n<=200:
  print((n-100)*5)

else:
  print(((n-200)*10)+500)

2000


In [ ]:
#find number of digits in a number

c=0

n=1234
while n>0:
  n=n//10
  c+=1

c

4

In [ ]:
n=1234

a=str(1234)
print(len(a))

4


In [ ]:
#wap to compute sum of digits in a given number
n=153

a=n

j=len(str(n))
s=0
while n>0:
  l=n%10
  s+=l**j
  n=n//10

if a==s:
  print("armstrong")

else:
  print("not armstrong")


armstrong


In [ ]:
n=1234
st=str(n)
s=0
for i in st:
  s=s+int(i)

s

10

In [ ]:
#wap to compute sum of squares of digits in a given number

n=3214

In [ ]:
#nested loop
for i in range(2):
  for j in range(4):
    print("*",end=" ")
  print()  #new line


* * * * 
* * * * 


In [ ]:
for i in range(3,6):
  for j in range(1,5):
    print(i*i,end=" ")

  print()

9 9 9 9 
16 16 16 16 
25 25 25 25 


In [ ]:
for i in range(4):
  for j in range(4-i):
    print(j,end=" ")
  print()

0 1 2 3 
0 1 2 
0 1 
0 


In [ ]:
for i in range(4):

  for j in range(4-i):
    print(" ",end=" ")

  for k in range(i+1):
    print("*",end=" ")

  for l in range(i):
    print("*",end=" ")

  print()

for i in range(4):

  for j in range(4-i):
    print(" ",end=" ")

  for k in range(i+1):
    print("*",end=" ")

  for l in range(i):
    print("*",end=" ")

  print()

        * 
      * * * 
    * * * * * 
  * * * * * * * 
        * 
      * * * 
    * * * * * 
  * * * * * * * 


In [ ]:
for i in range(1,5):
  for j in range(1,i+1):
    print(j,end=" ")
  print()e

1 
1 2 
1 2 3 
1 2 3 4 


In [ ]:
for i in range(1,5):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()

1 
2 1 
3 2 1 
4 3 2 1 


In [ ]:
l=["a","b","c","d"]

for i in range(4):
  for j in range(i+1):
    print(l[j],end=" ")
  print()

a 
a b 
a b c 
a b c d 


In [ ]:
#jumping statements
#pass

# for i in range(1,10):
#   if i%2==0:
#     pass
#   else:
#     print(i)

#break

# for i in range(1,10):
#   if i==5:
#     break
#   print(i)


#continiue

for i in range(1,10):
  if i==5:
    continue
  print(i)

1
2
3
4
6
7
8
9


In [ ]:
#wap to print prime numbers in a given range

for i in range(1,11):
  if i>1:
    for j in range(2,i):
      if i%j==0:
        break
    else:
      print(i)

2
3
5
7


In [ ]:
for i in range(5,5):
  print(i)

In [ ]:
#functions in python

#built in function print(),max(),len(),count()........

#function imported from modules

#user defined functions

In [ ]:

def add(a,b):
  return a+b,a-b


a=int(input("enter the number"))
b=int(input("entere the number"))

t,s=add(a,b)

print(t)
print(s)

enter the number4
entere the number5
9
-1


In [ ]:
#write a programe to create a function for addition substraction multiplication and division

In [ ]:
#create function to print factorial of a number

def fact(n):
  f=1
  for i in range(1,n+1):
    f=f*i

  return f

fact(5)

120

In [ ]:
#create a simple calculator using function

In [ ]:
#create a function to check a number is prime or not

In [ ]:
#wap to read list of numbers and create a function to find the maximum element without using inbuilt function


l=input().split()

def max1(l):

  mx=0

  for i in l:
    if int(i)>mx:
      mx=int(i)

  return mx

max1(l)

3 4 2 1 7 3 2


7

In [ ]:
#create a function to check a number is odd or even

In [ ]:


def student(name,rollno=13): #default arguments
  print("name is : ",name)
  print("rollno is: ",rollno)

student(rollno=12,name="apple") #keyword arguments

name is :  apple
rollno is:  12


In [ ]:
#create a function to print area of a circle using difault and keyword arguent

def area(r,pi=3.14):
  print("area is: ",pi*(r**2))


area(r=9,pi=6.1)

area is:  494.09999999999997


In [ ]:
#create a function to find maximum of three numbers

def maxi(a,b,c):
  return max(a,b,c)


maxi(1,2,3)

3

In [ ]:
#create a function to reverse a string

def rev(s):
  return s[-1::-1]

rev("malayalam")

'malayalam'

In [ ]:
#create a function to check a string is palindrome or not

In [ ]:
#*args ,**kwargs


def ore(*args):
  print(type(args))

  for i in args:
    print(i)


ore(1,2,3,4,5,"apple")

<class 'tuple'>
1
2
3
4
5
apple


In [ ]:
def are(*args,**kwargs):
  print(type(kwargs))

  for k,v in kwargs.items():
    print(k,v)

  print(args)


are(3,4,5,a=1,b=2)

<class 'dict'>
a 1
b 2
(3, 4, 5)


In [ ]:
#searching
#linear search
#binary search

l=[4,5,6,1,2]

key=10

for i in l:
  if i==key:
    print("item found")
    break

else:
  print("item not found")

item not found


In [ ]:
l=[5,7,9,13,32,33,42,54,56,88]

l.sort()
key=88

u=len(l)-1
lo=0

while(lo<=u):
  mid=(u+lo)//2

  if l[mid]<key:
    lo=mid+1
  elif l[mid]>key:
    u=mid-1
  else:
    print("item found",mid)
    break

else:
  print("item not found")

item found 9


In [ ]:
#functional programing

#lambda function
#filter
#map
#list comprehension

In [ ]:

def sq(a):
  return a**2

sq(3)

9

In [ ]:
sq=lambda a:a*a

sq(5)

25

In [ ]:
#create a lambda function to compute sum of two numbers

su=lambda a,b:a+b

su(3,4)

7

In [ ]:
#create a lamda functin to compute average of three numbers

av=lambda a,b,c:(a+b+c)/3

av(2,3,4)

3.0

In [ ]:
#create a lambda function to find largest amoung two numbers

ge=lambda a,b:print("a is greater") if a>b else print("b is greater")

ge(4,5)

b is greater


In [ ]:
#wap to check a number is odd or even using lambda function

oe=lambda n:print("even") if n%2==0 else print("odd")

oe(3)

odd


In [ ]:
#wap to check a letter is vowlel or not using lambda function

ch=lambda a:print("vowel") if a.lower() in "aeiou" else print("not vowel")


ch("t")

not vowel


In [ ]:
#map

l=input().split()


a=list(map(int,l))

a

1 2 3 4


[1, 2, 3, 4]

In [ ]:
#wap to converte each elemetn in a list to float

l=[1,2,3,4]

a=list(map(float,l))
a

[1.0, 2.0, 3.0, 4.0]

In [ ]:
a=list(range(1,10,2))
a

[1, 3, 5, 7, 9]

In [ ]:
l=["a","ab","abc"]

list(map(list,l))

[['a'], ['a', 'b'], ['a', 'b', 'c']]

In [ ]:
def ad(a):
  return a+10

l=[1,2,3,4]

list(map(ad,l))

[11, 12, 13, 14]

In [ ]:
#wap to convert each element in the list to their squares

l=[1,2,3,4]

list(map(lambda a:a**2,l))

[1, 4, 9, 16]

In [ ]:

l1=[1,2,3,4]
l2=[6,7,8,9]

list(map(lambda a,b:a+b,l1,l2))

[7, 9, 11, 13]

In [ ]:
#wap to print sum of squares of each element in the given list
l1=[1,2,3,4]
l2=[6,7,8,9]

list(map(lambda a,b:a**2+b**2,l1,l2))

[37, 53, 73, 97]

In [ ]:
#wap to convert each elemetn in a given lsit to upper case

l=["aPPLe","OraNGe","ManGo"]

list(map(str.lower,l))

list(map(lambda x:x.upper(),l))

['APPLE', 'ORANGE', 'MANGO']

In [ ]:
l=[1,2,3,4]

list(filter(lambda x:x%2==0,l))

[False, True, False, True]

In [ ]:
#wap to extract odd numbers from given list
l=[1,2,3,4,5,6]

list(filter(lambda x:x%2!=0,l))

[1, 3, 5]

In [ ]:
#wap to return words which has more than 5 charecters

l=["apple","orange","grape","mango"]

list(filter(lambda x:len(x)>5,l))

['orange']

In [ ]:
#wap to create list of odd numbers and even numbers from exisitng list

l=[1,2,3,4,5,6,7,8]

odd=list(filter(lambda x:x%2!=0,l))
even=list(filter(lambda x:x%2==0,l))

print(odd)

print(even)

[1, 3, 5, 7]
[2, 4, 6, 8]


In [ ]:
#list comprehension

l=[i for i in range(1,11)]

l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#create a list wiht 10 "hi" using list comprehension

l=["hi" for i in range(10)]

l

['hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi']

In [ ]:
#wap to find squares of numbers from 1,10 in list format
l=[i**2 for i in range(1,11)]

l

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
#create a list of odd numbers from 1,15 using list comprehension

l=[x for x in range(1,16) if x%2!=0]

l

[1, 3, 5, 7, 9, 11, 13, 15]

In [ ]:
#add 10 with each element in given list

l=[1,2,3,4,5]

l1=[i+10 for i in l]

l1

[11, 12, 13, 14, 15]

In [ ]:
#filter even numbers from the given list using list comprehension

l=[1,2,3,4,5]

l1=[x for x in l if x%2==0]

l1

[2, 4]

In [ ]:
#create list of even numbers from 1,20 using list comprehension
l=[x for x in range(1,21) if x%2==0]
l
#wap to filter numbers greater than 5 usin list comprehension l=[1,2,55,4,3]
l=[1,2,55,4,3]
l=[x for x in l if x>5]
l
#l=["apple","orange","banana"] wap to print list of fruits except banana
l=["apple","orange","banana"]

l=[x for x in l if x!="banana"]
l
#find all numbers between 1-1000 which are multiples of 8 in list format

l=[x for x in range(1,1001) if x%8==0]

#crete a list of words which has p in it from the given list
l=["apple","mango","boy","popy"]
l=[x for x in l if "p" in x]
l

#create list of numbers from 1-100 which has 6 in it

l=[x for x in range(1,101) if "6" in str(x)]
l

[6, 16, 26, 36, 46, 56, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 76, 86, 96]

In [ ]:
#wap to print a number is odd or even in a given list

l=[2,3,4,5,6,6]

l=["even" if i%2==0 else "odd" for i in l]
l

['even', 'odd', 'even', 'odd', 'even', 'even']

In [ ]:
l=["jasmine","lotus","lilly","rose"]

#wap to print jasmine if it is jasmine else print flower

l=["jasmine" if x=="jasmine" else "flower" for x in l]
l

['jasmine', 'flower', 'flower', 'flower']

In [ ]:
#write a function that takes a number as parameter and display its factorial using
# 1.no parameter no return,
# 2.with parameter no return,
# 3.no parameter with retrun,
# 4.with parameter with return


def fun():
  n=int(input("enter the number"))

In [ ]:
import math

In [ ]:
print(math.ceil(2.3))

3


In [ ]:
#find 2 power 4 using math module

print(math.pow(2,4))

16.0


In [ ]:
#find factorial of a number using math module

print(math.factorial(5))

120


In [ ]:
#find square root of a number using math module

print(math.sqrt(16))

4.0


In [ ]:
from math import factorial,sqrt,sin

In [ ]:
factorial(5)

120

In [ ]:
#import pow ,cos,floor from math module and execute the same

from math import pow,cos,floor
pow(1,2)
cos(34)
floor(3.2)

3

In [ ]:
from math import *

In [ ]:
ceil(3)

3

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [ ]:
import calculator

In [ ]:
calculator.add(1,2)

3

In [ ]:
from calculator import sub

In [ ]:
import calculator

In [ ]:
sub(4,3)

1

In [ ]:
help(calculator)

Help on module calculator:

NAME
    calculator - calculator.ipynb

DESCRIPTION
    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1JUoegB1RN--E0ODbu8zL05Zu40D3KOlF

FUNCTIONS
    add(a, b)

    sub(a, b)

FILE
    /content/calculator.py




In [ ]:
#create a module to print prime numbers in a given range,string reversal,factorial

In [ ]:
f1=open("/content/drive/MyDrive/file1.txt","r")


#readlines()
#list format

f=f1.readlines()
for i in f:
  print(i.strip())

print(type(f))

f1.close()

first line
second line
third line
<class 'list'>


In [ ]:
#read the content form file1 using readlines and list comprehension

f1=open("/content/drive/MyDrive/file1.txt","r")

f=f1.readlines()
print(f)

l=[i.strip() for i in f]

for i in l:
  print(i)

print(l)

f1.close()

['first line\n', 'second line\n', 'third line']
first line
second line
third line
['first line', 'second line', 'third line']


In [ ]:
#read content form the file1 and convert it into capital letters
f1=open("/content/drive/MyDrive/file1.txt","r")

l=f1.readlines()
print(l)

l=[i.strip().upper() for i in l]

print(l)

for i in l:
  print(i)

f1.close()

['first line\n', 'second line\n', 'third line']
['FIRST LINE', 'SECOND LINE', 'THIRD LINE']
FIRST LINE
SECOND LINE
THIRD LINE


In [ ]:
#readline()
f1=open("/content/drive/MyDrive/file1.txt","r")

f=f1.readline()
print(f)
print(type(f))

a=f1.readline()
print(a)

f1.close()

first line

<class 'str'>
second line



In [ ]:
#read()

f1=open("/content/drive/MyDrive/file1.txt","r")

f=f1.read(2)
f=f1.read(2)
f=f1.read(2)
f=f1.tell()

f1.seek(0)

f=f1.read(2)

print(f)
print(type(f))

f1.close()

fi
<class 'str'>


In [ ]:
f2=open("/content/drive/MyDrive/file2.txt","w")
#write

f2.write("hello\n")
f2.write("hi\n")
f2.write("bye\n")

f2.close()

In [ ]:
#writelines()
f2=open("/content/drive/MyDrive/file2.txt","a")

l=["good\n","morning\n","dear\n"]

f2.writelines(l)

f2.close()

In [ ]:
#copy the content from first file to second
f1=open("/content/drive/MyDrive/file1.txt","r")
f2=open("/content/drive/MyDrive/file2.txt","w")

l=f1.readlines()

f2.writelines(l)

f1.close()
f2.close()

In [ ]:
#find number of lines in file1

f1=open("/content/drive/MyDrive/file1.txt","r")

l=f1.read()

print(l.count("\n")+1)

f1.close()

3


In [ ]:
#find occuacne of each word in a file
f1=open("/content/drive/MyDrive/file1.txt","r")

f=f1.read()
l=f.split()
print(l)

d={}

for i in l:
  if i not in d:
    d[i]=1
  else:
    d[i]+=1

print(d)

f1.close()

['first', 'line', 'second', 'line', 'third', 'line']
{'first': 1, 'line': 3, 'second': 1, 'third': 1}


In [ ]:
#write a line to the file and read the same

seek(0)

In [ ]:
#wap to count the even numbers from 800-1000 both inclusive
#wap that counts the number of century years from 1800 to 2500
#wap that displays the first 10 triangular numbers(A number that can form an equlateral triangle.The nth triangular number is the sum of the first n natural numbers For example,the third triangular number is 1+2+3=6)
#wap to print the following pattern

*
# #
. * *
# # # #
. * * * *
# # # # # #

#wap to print the following pattern
1
1 4
1 4 9
1 4 9 16
1 4 9 16 25
1 4 9 16 25 36




In [ ]:
#wap  that ask the user to input their name,weight,height and using these data find BMI and inform user that which category they are in according to the following
#BMI categories:
#underweight= <18.5
#normal weight=18.5-24.9
#over weight= 25-29.9
#obesity =BMI of 30 or greater

#wap that asks the user to input thir score(0-100) and then outputs corresponding grade accordng to the following scale:

# 90-100:A
# 80-89:B
# 70-79:C
# 60-69:D
# below 60:F

SyntaxError: illegal target for annotation (ipython-input-693021861.py, line 10)

In [ ]:
#wap that asks the user to input a number and determine if that number is an odd number greater than 10

#wap that asks the user to input a letter from the english alphabet and display whether the character is vowel or consonant

#wap that asks the user to input a year and display whether the year is leap year or not

#wap  that asks a user to input diameter of a circle and calculate the area of the circle and display it

In [ ]:
#regular expressions

import re

#match
#search
#sub
#findall

s="python is a good programming is language"

re.match("python",s) #starting with
print(re.match("is",s))

None


In [ ]:
#search

re.search("is",s)

<re.Match object; span=(7, 9), match='is'>

In [ ]:
#findall

re.findall("is",s)

['is', 'is']

In [ ]:
#sub

re.sub("is","was",s)

'python was a good programming was language'

In [ ]:
#wap to search a particular word in a given string using re

s="apples are oranges"

re.search("are",s)

<re.Match object; span=(7, 10), match='are'>

In [ ]:
s="python1 is 333 good programming language ABCD"

re.sub("[a-dA-D]","@",s)
re.sub("[^a-z A-Z]","@",s)

re.sub("[^a-z A-Z]","",s)

re.sub("[a-d]","@",s)

# re.sub("\d","",s)

re.sub("[0-9]","",s)

re.sub(r"\d","",s)

'python is  good programming language ABCD'

In [ ]:
s="123,455"

re.findall("/d",s)

[]

In [ ]:
from string import whitespace
s="1234 apple 54ora5ngee are"


re.sub(r"\s","9",s)

# \s: to remove whitespace
# \d:to remove digits
# \D:to remove alphabets

'12349apple954ora5ngee9are'

In [ ]:
#recurssion :a function calling itself

In [ ]:
#wap to find factorial of a numbr using recurssion


def fact(n):
  return n*fact(n-1)


fact(5)

RecursionError: maximum recursion depth exceeded

In [ ]:
#wap to find sum of n natural numbers using recursion
def s(n):
  if n==1:
    return 1
  else:
    return n+s(n-1)

s(5)

15

In [ ]:
class Student():

  def get_data(self):
    self.name=input("enter the name")
    self.rollno=int(input("enter the roll no"))

  def display_data(self):
    print(self.name)
    print(self.rollno)



s1=Student()

s1.get_data()

s1.display_data()

s2=Student()

enter the nameabu
enter the roll no1
abu
1


In [ ]:
#create a class rectangle and display ists area and perimeter

class Rectangle():
  def get_data(self):
    self.l=int(input("enter teh length"))
    self.b=int(input("enter teh bredth"))

  def area(self):
    print("area: ",self.l*self.b)

  def perimenter(self):
    print("perimeter=",2*(self.l+self.b))

r=Rectangle()

r.get_data()
r.area()
r.perimenter()

r1=Rectangle()
r1.get_data()

r1.area()


enter teh length3
enter teh bredth4
area:  12
perimeter= 14
enter teh length5
enter teh bredth6
area:  30


In [ ]:
#create class of circles display area perimeter

In [ ]:
#constructor: __init__() to assign values to data members , automatically calls when object is created

In [ ]:
class Student():

  def __init__(self,n,r):
    self.name=n
    self.rollno=r

  def display_data(self):
    print(self.name)
    print(self.rollno)


s1=Student("abu",1)

s1.display_data()

abu
1


In [ ]:
#create class recatangle with constructor

class Rectangle():

  def __init__(self,l,b):
    self.length=l
    self.bredth=b

  def area(self):
    print("area=",self.length*self.bredth)

  def perimeter(self):
    print("perimeter=",2*(self.length+self.bredth))

r=Rectangle(4,5)
# r.get_data()

r.area()

r.perimeter()

area= 20
perimeter= 18


In [ ]:
#create class circle using constructor

In [ ]:
#find string reversal using class

In [ ]:
#exception handling in python

In [ ]:
n=int(input("enter the number"))
d=int(input("enter the denominator"))

try:
  print(n/d)
except ZeroDivisionError:
  print("error due to zero division")

except ValueError:
  print("error due to value error")

except TypeError:
  print("error due to type error")

except:
  print("error")



enter the number4
enter the denominator7
0.5714285714285714


In [ ]:
n=int(input("enter the number"))
d=int(input("enter the denominator"))

try:
  a=n/d

except:
  print("error occured")


else:
  print(a)

finally:
  print("hi")


enter the number6
enter the denominator7
0.8571428571428571
hi


In [ ]:
print("gf"/0)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [ ]:
class Rectangle():

  def __init__(self,l,b):
    self.__length=l
    self.bredth=b

  def area(self):
    print("area=",self.__length*self.bredth)

  def perimeter(self):
    print("perimeter=",2*(self.__length+self.bredth))

r=Rectangle(4,5)

#public
# print(r.length)
# r.area()
# r.perimeter()

#protected
# r.area()

# print(r._length)

#private

r.area()
r.perimeter()

print(r.__length)



area= 20
perimeter= 18


AttributeError: 'Rectangle' object has no attribute '__length'

In [ ]:
#inheritance

#create a class student
  #name
  #rollno
    #get_data()
    #display_data()

class Student():
  def __init__(self,n,r):
    self.name=n
    self.rollno=r

  def display(self):
    print(self.name)
    print(self.rollno)


#create a class grade
  #mark
    #readmark()
    #displaymark()
    #calgrade()
      #mark>80  grade  A
      #mark>50 grade B
      #else faild

class Grade(Student):
  def __init__(self,n,r,m):
    super().__init__(n,r)
    self.mark=m

  def display(self):
    super().display()
    # print(self.mark)

  def cal_grade(self):
    if self.mark>80:
      print("grade A")
    elif self.mark>50:
      print("grade B")
    else:
      print("fail")

s1=Grade("apple",34,90)

s1.display()



apple
34
90


In [ ]:
#student():
  #name
  #rollno
    #get_data()
    #display_data()

class Student():
  def __init__(self,n,r):
    self.name=n
    self.rollno=r

  def display_data(self):
    print(self.name)
    print(self.rollno)

#test(student):
   #testmark
     #read_tmark()
     #display_tmark()

class Test(Student):

  def __init__(self,n,r,t):
    Student.__init__(self,n,r)
    self.testmark=t

  def display_tmark(self):
    print(self.testmark)


#sports():
  #smark
    #read_smark()
    #display_smark()

class Sports():
  def __init__(self,s):
    self.smark=s

  def display_smark(self):
    print(self.smark)

#grade(test,sports)
 #tm=testmark + smark
   #calgrade()

class Grade(Test,Sports):

  def __init__(self,n,r,t,s):
    Test.__init__(self,n,r,t)
    Sports.__init__(self,s)



  def cal_grade(self):
    self.tm=self.testmark+self.smark

    if self.tm>80:
      print("grade A")
    elif self.tm>50:
      print("grade B")
    else:
      print("fail")

g1=Grade("abu",22,54,89)
g1.display_data()
g1.display_tmark()
g1.display_smark()
g1.cal_grade()

# g1.get_data()  #student
# g1.read_tmark()#test
# g1.read_smark()#sports
# g1.display_smark()
# g1.cal_grade() #grade


abu
22
54
89
grade A


In [ ]:
#polymorphsm

class Point():
  def __init__(self,x,y):
    self.x=x
    self.y=y

  def __add__(self,other):
    x=self.x+other.x+10
    y=self.y+other.y+10
    return Point(x,y)

  def __str__(self):
    return "({0},{1})".format(self.x,self.y)

p1=Point(1,2)
p2=Point(5,6)
print(p1+p2)

(6,6)


In [ ]:
# # # #
# # # #
# # # #


for i in range(3):
  for j in range(4):
    print(i,end=" ")

  print()

0 0 0 0 
1 1 1 1 
2 2 2 2 


In [ ]:
for i in range(4):
  for j in range(4-i):
    print("#",end=" ")

  print()

# # # # 
# # # 
# # 
# 


In [ ]:
import numpy as np #numerical python

#array  collection of data with same datatype(Homogenious)

a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing forward slicing backward slicing

b=np.array([1,2,3,4,5])

#print 1,2

b[0:2]
# print 5,4

b[-1:-3:-1]

# print 4,5

b[3:]

# print 2,1
b[-4::-1]

array([2, 1])

In [ ]:
#diamension

a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])

a.ndim  #diamension=1 vector

b.ndim #diamesion =2 matrix

print(b)

b.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,
                    #4,5

z=np.array([[2,3],[4,5]])

print(z)

print(z.shape)

print(z.ndim)

print(z.size)

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print ,size,shape,diamension

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.size)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
6
2


In [ ]:
#create 4x2 matrix display its  size shape diamension

In [ ]:
#create a 4x4 matrix
import numpy as np

z=np.array([[1,2,3,4],[5,3,2,2],[7,6,5,3],[3,4,3,2]])
print(z)


[[1 2 3 4]
 [5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]


In [ ]:
z[0]

z[:,0]

z[1,1]

z[2,2]

z[3,2:]

z[2:,2:]

array([[5, 3],
       [3, 2]])

In [ ]:
#zero matrix


z=np.zeros([2,3,3],dtype=int)

z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create two 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition

print(a+b)

#matrix substraction

print(a-b)

#matrix multiplicatione

print(a*b) #not a matrix multiplication

print(a@b) #matrix multiplication

print(a.dot(b)) #matrix multiplication

#matrix division

print(a/b)

[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[ 3  2]
 [18 28]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]
[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix

z=np.full([3,3],7,dtype=int)

z

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#create 3x4 matirx with value 9 and datatype complex

In [ ]:
#identity matrix

# z=np.identity(3,dtype=int)
# z

z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)

print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(16,1)
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [ ]:
#arange

a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange

z=np.arange(1,11).reshape(5,2)
z

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matirx with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [ ]:
#floor

z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [ ]:
#round


z=np.round(a)
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [10]:
#create a 3x3 matrix
import numpy as np

a=np.arange(1,10).reshape(3,3)
print(a)

a.max()

a.max(axis=1)

a.max(axis=0)


a.min()

a.min(axis=1)

a.min(axis=0)


a.sum()

a.sum(axis=1)

a.sum(axis=0)


np.sqrt(a)

np.sin(a)

np.cos(a)

np.tan(a)

#flatten

a.flatten()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#sort
#create 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])

print(a)

b=np.sort(a,axis=1)
print(b)

c=np.argsort(a,axis=1)
print(c)

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
